/**
 * Umschlag OpenAPI
 * API definition for Umschlag
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient'

/**
 * The InlineObject model module.
 * @module umschlag/model/InlineObject
 * @version 1.0.0-alpha1
 */
class InlineObject {
  /**
     * Constructs a new <code>InlineObject</code>.
     * @alias module:umschlag/model/InlineObject
     * @param username {String}
     * @param password {String}
     */
  constructor (username, password) {
    InlineObject.initialize(this, username, password)
  }

  /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
  static initialize (obj, username, password) {
    obj['username'] = username
    obj['password'] = password
  }

  /**
     * Constructs a <code>InlineObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:umschlag/model/InlineObject} obj Optional instance to populate.
     * @return {module:umschlag/model/InlineObject} The populated <code>InlineObject</code> instance.
     */
  static constructFromObject (data, obj) {
    if (data) {
      obj = obj || new InlineObject()

      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String')
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String')
      }
    }
    return obj
  }
}

/**
 * @member {String} username
 */
InlineObject.prototype['username'] = undefined

/**
 * @member {String} password
 */
InlineObject.prototype['password'] = undefined

export default InlineObject
