/**
 * Umschlag OpenAPI
 * API definition for Umschlag
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient'

/**
 * The TeamUserParams model module.
 * @module umschlag/model/TeamUserParams
 * @version 1.0.0-alpha1
 */
class TeamUserParams {
  /**
     * Constructs a new <code>TeamUserParams</code>.
     * @alias module:umschlag/model/TeamUserParams
     * @param team {String}
     * @param user {String}
     * @param perm {String}
     */
  constructor (team, user, perm) {
    TeamUserParams.initialize(this, team, user, perm)
  }

  /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
  static initialize (obj, team, user, perm) {
    obj['team'] = team
    obj['user'] = user
    obj['perm'] = perm
  }

  /**
     * Constructs a <code>TeamUserParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:umschlag/model/TeamUserParams} obj Optional instance to populate.
     * @return {module:umschlag/model/TeamUserParams} The populated <code>TeamUserParams</code> instance.
     */
  static constructFromObject (data, obj) {
    if (data) {
      obj = obj || new TeamUserParams()

      if (data.hasOwnProperty('team')) {
        obj['team'] = ApiClient.convertToType(data['team'], 'String')
      }
      if (data.hasOwnProperty('user')) {
        obj['user'] = ApiClient.convertToType(data['user'], 'String')
      }
      if (data.hasOwnProperty('perm')) {
        obj['perm'] = ApiClient.convertToType(data['perm'], 'String')
      }
    }
    return obj
  }
}

/**
 * @member {String} team
 */
TeamUserParams.prototype['team'] = undefined

/**
 * @member {String} user
 */
TeamUserParams.prototype['user'] = undefined

/**
 * @member {String} perm
 */
TeamUserParams.prototype['perm'] = undefined

export default TeamUserParams
