---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: prepare
  image: webhippie/nodejs:latest
  pull: always
  commands:
  - yarn install --frozen-lockfile

- name: lint
  image: webhippie/nodejs:latest
  pull: always
  commands:
  - yarn lint
  depends_on:
  - prepare

- name: test
  image: webhippie/nodejs:latest
  pull: always
  commands:
  - yarn test
  depends_on:
  - prepare

- name: build
  image: webhippie/nodejs:latest
  pull: always
  commands:
  - yarn build
  depends_on:
  - prepare

- name: release
  image: plugins/npm:1
  pull: always
  settings:
    token:
      from_secret: npm_token
  when:
    event:
    - tag
  depends_on:
  - build

- name: notify
  image: plugins/matrix:1
  pull: always
  settings:
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    event:
    - push
    - tag
    status:
    - failure
  depends_on:
  - prepare
  - lint
  - test
  - build
  - release

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
