/**
 * Umschlag OpenAPI
 * API definition for Umschlag
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd() + '/src/umschlag/index'], factory)
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd() + '/src/umschlag/index'))
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Umschlag)
  }
}(this, function (expect, Umschlag) {
  'use strict'

  // eslint-disable-next-line no-unused-vars
  var instance

  beforeEach(function () {
    instance = new Umschlag.TeamApi()
  })

  /* eslint-disable no-unused-vars */
  var getProperty = function (object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function') { return object[getter]() } else { return object[property] }
  }
  /* eslint-enable no-unused-vars */

  /* eslint-disable no-unused-vars */
  var setProperty = function (object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function') { object[setter](value) } else { object[property] = value }
  }
  /* eslint-enable no-unused-vars */

  describe('TeamApi', function () {
    describe('appendTeamToUser', function () {
      it('should call appendTeamToUser successfully', function (done) {
        // uncomment below and update the code to test appendTeamToUser
        // instance.appendTeamToUser(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done()
      })
    })
    describe('createTeam', function () {
      it('should call createTeam successfully', function (done) {
        // uncomment below and update the code to test createTeam
        // instance.createTeam(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done()
      })
    })
    describe('deleteTeam', function () {
      it('should call deleteTeam successfully', function (done) {
        // uncomment below and update the code to test deleteTeam
        // instance.deleteTeam(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done()
      })
    })
    describe('deleteTeamFromUser', function () {
      it('should call deleteTeamFromUser successfully', function (done) {
        // uncomment below and update the code to test deleteTeamFromUser
        // instance.deleteTeamFromUser(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done()
      })
    })
    describe('listTeamUsers', function () {
      it('should call listTeamUsers successfully', function (done) {
        // uncomment below and update the code to test listTeamUsers
        // instance.listTeamUsers(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done()
      })
    })
    describe('listTeams', function () {
      it('should call listTeams successfully', function (done) {
        // uncomment below and update the code to test listTeams
        // instance.listTeams(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done()
      })
    })
    describe('permitTeamUser', function () {
      it('should call permitTeamUser successfully', function (done) {
        // uncomment below and update the code to test permitTeamUser
        // instance.permitTeamUser(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done()
      })
    })
    describe('showTeam', function () {
      it('should call showTeam successfully', function (done) {
        // uncomment below and update the code to test showTeam
        // instance.showTeam(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done()
      })
    })
    describe('updateTeam', function () {
      it('should call updateTeam successfully', function (done) {
        // uncomment below and update the code to test updateTeam
        // instance.updateTeam(function(error) {
        //  if (error) throw error;
        // expect().to.be();
        // });
        done()
      })
    })
  })
}))
